name:                predestination-dating-sim-backend
version:             0.1.0.0
github:              "MajronMan/predestination-dating-sim"
license:             BSD3
author:              "Miron Markowski"
maintainer:          "majron15@gmail.com"
copyright:           "2020 Miron Markowski"

extra-source-files:
- README.md
- ChangeLog.md

default-extensions:
  - NoImplicitPrelude
  - OverloadedStrings
  - OverloadedLabels 
  - DeriveGeneric

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/MajronMan/predestination-dating-sim#readme>

dependencies:
- base >= 4.7 && < 5
- universum
- warp
- wai
- selda
- selda-postgresql
- selda-json
- utf8-string
- bytestring
- http-types
- dotenv
- aeson
- containers

library:
  source-dirs: src

executables:
  predestination:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - predestination-dating-sim-backend

tests:
  predestination-dating-sim-backend-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - predestination-dating-sim-backend
